CREATE TABLE NOTES_T (
    note_id TEXT NOT NULL PRIMARY KEY,
    note_name TEXT NOT NULL
) WITHOUT ROWID;

CREATE TABLE RELATIONS_T (
    relation_id TEXT NOT NULL PRIMARY KEY,
    parent_id TEXT NOT NULL,
    child_id TEXT NOT NULL
) WITHOUT ROWID;

CREATE TABLE TABLES_T (
    table_id TEXT NOT NULL PRIMARY KEY,
    table_name TEXT NOT NULL,
    note_id TEXT NOT NULL
) WITHOUT ROWID;

CREATE TABLE CELL_T (
    cell_id TEXT NOT NULL PRIMARY KEY,
    table_id TEXT NOT NULL,
    cell_name TEXT NOT NULL,
    cell_note TEXT NOT NULL,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP DEFAULT NULL,
    is_notify INT DEFAULT 0
) WITHOUT ROWID;